//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicArea
    {
        public int AcademicAreaID { get; set; }
        public string AcademicAreaName { get; set; }
        public Nullable<int> AcademicDepartmentID { get; set; }
    }
}
