//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdjustmentDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdjustmentDetail()
        {
            this.AdjustmentDetailFees = new HashSet<AdjustmentDetailFee>();
        }
    
        public int AdjustmentDetailsID { get; set; }
        public Nullable<int> AdjustmentID { get; set; }
        public Nullable<int> ScheduleID { get; set; }
        public Nullable<bool> Action { get; set; }
        public Nullable<double> TuitionFee { get; set; }
        public Nullable<double> AirconFee { get; set; }
        public Nullable<double> LaboFee { get; set; }
        public Nullable<double> OtherFee { get; set; }
        public Nullable<double> AdjDiscount { get; set; }
        public Nullable<double> AdjDiscountA { get; set; }
        public Nullable<double> AdjDiscountL { get; set; }
        public Nullable<double> AdjDiscountO { get; set; }
        public Nullable<double> AdjTotalT { get; set; }
        public Nullable<double> AdjTotalA { get; set; }
        public Nullable<double> AdjTotalL { get; set; }
        public Nullable<double> AdjTotalO { get; set; }
        public Nullable<double> RefundRate { get; set; }
        public Nullable<int> LabFeeID { get; set; }
        public Nullable<int> OtherFeeID { get; set; }
        public bool Locked { get; set; }
    
        public virtual Adjustment Adjustment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdjustmentDetailFee> AdjustmentDetailFees { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
