//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adjustment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Adjustment()
        {
            this.AdjustmentDetails = new HashSet<AdjustmentDetail>();
        }
    
        public int AdjustmentID { get; set; }
        public int StudentSectionID { get; set; }
        public Nullable<int> PaymentID { get; set; }
        public System.DateTime AdjustmentDate { get; set; }
        public string AdjustedBy { get; set; }
        public Nullable<System.DateTime> ValidationDate { get; set; }
        public string Remarks { get; set; }
    
        public virtual Payment Payment { get; set; }
        public virtual Student_Section Student_Section { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdjustmentDetail> AdjustmentDetails { get; set; }
    }
}
