//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdmissionExamResult
    {
        public int ExamDateID { get; set; }
        public int ApplicationNo { get; set; }
        public int TestResult { get; set; }
        public string InterviewResult { get; set; }
        public string Recommendation { get; set; }
    
        public virtual AdmissionExamDate AdmissionExamDate { get; set; }
        public virtual AdmissionExamResultType AdmissionExamResultType { get; set; }
        public virtual StudentApplication StudentApplication { get; set; }
    }
}
