//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdmissionMarketingEffortsSchool
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdmissionMarketingEffortsSchool()
        {
            this.AdmissionMarketingEffortsCareerFairs = new HashSet<AdmissionMarketingEffortsCareerFair>();
            this.AdmissionMarketingEffortsCareerTalks = new HashSet<AdmissionMarketingEffortsCareerTalk>();
            this.AdmissionMarketingEffortsMaterials = new HashSet<AdmissionMarketingEffortsMaterial>();
        }
    
        public int SchoolID { get; set; }
        public string SchoolName { get; set; }
        public string SchoolAddress { get; set; }
        public string City { get; set; }
        public string ContactPerson { get; set; }
        public string Position { get; set; }
        public string ContactNo { get; set; }
        public Nullable<int> EnrolledStudents { get; set; }
        public string SchoolType { get; set; }
        public Nullable<bool> FairChk { get; set; }
        public Nullable<System.DateTime> FairDate { get; set; }
        public Nullable<int> FairNumParticipants { get; set; }
        public Nullable<bool> TalkChk { get; set; }
        public Nullable<System.DateTime> TalkDate { get; set; }
        public Nullable<int> TalkNumParticipants { get; set; }
        public Nullable<bool> MaterialsChk { get; set; }
        public Nullable<System.DateTime> MaterialsDate { get; set; }
        public Nullable<System.DateTime> SystemDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdmissionMarketingEffortsCareerFair> AdmissionMarketingEffortsCareerFairs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdmissionMarketingEffortsCareerTalk> AdmissionMarketingEffortsCareerTalks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdmissionMarketingEffortsMaterial> AdmissionMarketingEffortsMaterials { get; set; }
    }
}
