//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aircon
    {
        public int FeeID { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<int> YearLevel { get; set; }
    
        public virtual Fee Fee { get; set; }
    }
}
