//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Annoucement_Table
    {
        public int AnnoucementID { get; set; }
        public string AnnoucementTitle { get; set; }
        public string Annoucements { get; set; }
        public bool Active { get; set; }
        public bool ItemDelete { get; set; }
    }
}
