//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationSurveyDetail
    {
        public int ApplicationSurveyDetailsID { get; set; }
        public Nullable<int> ApplicationNo { get; set; }
        public Nullable<int> ApplicationSurveyID { get; set; }
        public string ApplicationSurveyValue { get; set; }
    
        public virtual ApplicationSurveyQuestion ApplicationSurveyQuestion { get; set; }
        public virtual StudentApplication StudentApplication { get; set; }
    }
}
