//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class APVoucher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APVoucher()
        {
            this.APVoucherDetails = new HashSet<APVoucherDetail>();
            this.CDSVouchers = new HashSet<CDSVoucher>();
        }
    
        public int APVoucherID { get; set; }
        public Nullable<int> APVDocNo { get; set; }
        public System.DateTime APVoucherDate { get; set; }
        public Nullable<System.DateTime> ReceivingDate { get; set; }
        public int PayeeID { get; set; }
        public string Remarks { get; set; }
        public string Particulars { get; set; }
        public int EncodedBy { get; set; }
        public bool Locked { get; set; }
        public int SchoolYearID { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public Nullable<int> CDSVoucherID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APVoucherDetail> APVoucherDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CDSVoucher> CDSVouchers { get; set; }
        public virtual Payee Payee { get; set; }
        public virtual CDSVoucher CDSVoucher { get; set; }
    }
}
