//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARMessage
    {
        public Nullable<int> Student_SectionID { get; set; }
        public string Message { get; set; }
        public int StudentID { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Student_Section Student_Section { get; set; }
    }
}
