//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceElementary
    {
        public int AttendanceElemID { get; set; }
        public Nullable<int> PeriodID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> Quarter { get; set; }
        public Nullable<int> Absences { get; set; }
        public string Core1 { get; set; }
        public string Core2 { get; set; }
        public string Core3 { get; set; }
        public Nullable<int> Tardy { get; set; }
    
        public virtual Period Period { get; set; }
        public virtual Student Student { get; set; }
    }
}
