//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class backelem
    {
        public string studno { get; set; }
        public string name { get; set; }
        public Nullable<double> amount { get; set; }
        public Nullable<System.DateTime> v_date { get; set; }
        public string p_mode { get; set; }
        public string period { get; set; }
        public string ar_year { get; set; }
        public bool paid { get; set; }
    }
}
