//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BackAccountCopy
    {
        public int BankAccountID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<double> N { get; set; }
        public Nullable<double> Balance { get; set; }
        public Nullable<int> SemID { get; set; }
        public Nullable<int> PaymentID { get; set; }
        public Nullable<int> Student_SectionID { get; set; }
    }
}
