//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BackAccountPayment
    {
        public int BackAccountPaymentID { get; set; }
        public Nullable<int> BackAccountID { get; set; }
        public Nullable<int> PaymentID { get; set; }
    
        public virtual BackAccount BackAccount { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
