//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class backpayment20161stsem
    {
        public string period { get; set; }
        public string studno { get; set; }
        public string pay_code { get; set; }
        public Nullable<System.DateTime> or_date { get; set; }
        public string or_no { get; set; }
        public Nullable<double> amount { get; set; }
        public string c_code { get; set; }
        public string tor { get; set; }
        public string ar_cd { get; set; }
        public string studname { get; set; }
        public string level_code { get; set; }
        public bool checkpay { get; set; }
        public string chkno { get; set; }
        public Nullable<double> chkamount { get; set; }
        public Nullable<System.DateTime> datestamp { get; set; }
    }
}
