//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BackAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BackAccount()
        {
            this.BackAccountPayments = new HashSet<BackAccountPayment>();
        }
    
        public int BankAccountID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<double> N { get; set; }
        public Nullable<double> Balance { get; set; }
        public Nullable<int> SemID { get; set; }
        public Nullable<int> PaymentID { get; set; }
        public Nullable<int> Student_SectionID { get; set; }
        public Nullable<int> DMCMID { get; set; }
        public Nullable<int> PeriodID { get; set; }
    
        public virtual DMCM DMCM { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual Period Period { get; set; }
        public virtual Period Period1 { get; set; }
        public virtual Student Student { get; set; }
        public virtual Student_Section Student_Section { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BackAccountPayment> BackAccountPayments { get; set; }
    }
}
