//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BalanceDueOverride
    {
        public int BalanceDueID { get; set; }
        public Nullable<int> SemID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> PaycodeID { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
    }
}
