//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankTransaction
    {
        public int BankTransactionID { get; set; }
        public int AcctID { get; set; }
        public int BankAccountID { get; set; }
        public double Amount { get; set; }
        public Nullable<int> TransactionID { get; set; }
        public string CheckNo { get; set; }
        public Nullable<int> CoaBankID { get; set; }
    
        public virtual Bank_Account Bank_Account { get; set; }
        public virtual ChartOfAccount ChartOfAccount { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
