//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashierDCR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CashierDCR()
        {
            this.CashierDCRVoids = new HashSet<CashierDCRVoid>();
        }
    
        public int CashierDCRID { get; set; }
        public string ReferencecNo { get; set; }
        public System.DateTime ReportDate { get; set; }
        public int D1000 { get; set; }
        public int D500 { get; set; }
        public int D200 { get; set; }
        public int D100 { get; set; }
        public int D50 { get; set; }
        public int D20 { get; set; }
        public int D10 { get; set; }
        public int D1 { get; set; }
        public int D25Cent { get; set; }
        public int D10Cent { get; set; }
        public int D5Cent { get; set; }
        public int D5 { get; set; }
        public Nullable<double> BankPayment { get; set; }
        public Nullable<double> CheckPayment { get; set; }
        public int CashierID { get; set; }
        public Nullable<double> CreditCardPayment { get; set; }
        public Nullable<double> DormCash { get; set; }
        public Nullable<double> DormCheck { get; set; }
        public Nullable<double> DormCreditCard { get; set; }
        public Nullable<double> RentalCash { get; set; }
        public Nullable<double> RentalCheck { get; set; }
        public Nullable<double> RentalCreditCard { get; set; }
        public string OldORNo { get; set; }
        public Nullable<double> OldCash { get; set; }
        public Nullable<double> OldCredit { get; set; }
        public Nullable<double> OldCheck { get; set; }
        public Nullable<int> TotalTransactions { get; set; }
    
        public virtual CashierDCRDetail CashierDCRDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashierDCRVoid> CashierDCRVoids { get; set; }
    }
}
