//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashierDCRVoid
    {
        public int CashierDCRVoidID { get; set; }
        public Nullable<int> CashierDCRID { get; set; }
        public string ORNo { get; set; }
    
        public virtual CashierDCR CashierDCR { get; set; }
    }
}
