//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashierDCRDetail
    {
        public int CashierDCRDetailsID { get; set; }
        public string StartOR { get; set; }
        public string EndOR { get; set; }
        public int CashierDCRID { get; set; }
    
        public virtual CashierDCR CashierDCR { get; set; }
    }
}
