//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeOfGradeDoctoral
    {
        public int ChangeOfGradeID { get; set; }
        public string NewGrade { get; set; }
        public string CompletionFormCode { get; set; }
        public Nullable<System.DateTime> DateFiled { get; set; }
        public Nullable<System.DateTime> DateEncoded { get; set; }
        public string EncodedBy { get; set; }
        public string OldGrade { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> PeriodID { get; set; }
        public string PrintedBy { get; set; }
    
        public virtual Period Period { get; set; }
        public virtual Student Student { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
