//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class changeofgrade2017
    {
        public string cfgno { get; set; }
        public string syear { get; set; }
        public string period { get; set; }
        public string studno { get; set; }
        public string subcode { get; set; }
        public string extend { get; set; }
        public string sectno { get; set; }
        public string oldgrade { get; set; }
        public string newgrade { get; set; }
        public string fcode { get; set; }
        public Nullable<System.DateTime> dateup { get; set; }
        public string edate { get; set; }
        public string valuser { get; set; }
        public bool printed { get; set; }
    }
}
