//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClubJH
    {
        public int JHSClubID { get; set; }
        public string ClubName { get; set; }
        public Nullable<int> PeriodID { get; set; }
        public Nullable<int> FacultyID { get; set; }
    }
}
