//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class coaold
    {
        public string acctno { get; set; }
        public string acctname { get; set; }
        public string accttype { get; set; }
        public bool sl_flg { get; set; }
        public bool dept_flg { get; set; }
    }
}
