//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class cocurr2016
    {
        public string period { get; set; }
        public string studno { get; set; }
        public string lastname { get; set; }
        public string firstname { get; set; }
        public string middle { get; set; }
        public string subcode { get; set; }
        public string sectno { get; set; }
        public string extend { get; set; }
        public string quarter1 { get; set; }
        public string quarter2 { get; set; }
        public string quarter3 { get; set; }
        public string quarter4 { get; set; }
        public string aircon { get; set; }
        public string var { get; set; }
        public string lab { get; set; }
        public string etype { get; set; }
        public Nullable<double> credit { get; set; }
        public string finalgrd { get; set; }
        public string date_up { get; set; }
        public bool locked { get; set; }
        public Nullable<double> absent { get; set; }
    }
}
