//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRSVoucher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CRSVoucher()
        {
            this.CRSVoucherDetails = new HashSet<CRSVoucherDetail>();
        }
    
        public int CRSVoucherID { get; set; }
        public string CRSVoucherDocNo { get; set; }
        public System.DateTime CRSVoucherDate { get; set; }
        public Nullable<int> CashierDCRID { get; set; }
        public string Particulars { get; set; }
        public int SchoolYearID { get; set; }
        public Nullable<bool> Incomplete { get; set; }
        public Nullable<int> PaymentID { get; set; }
    
        public virtual SchoolYear SchoolYear { get; set; }
        public virtual CRSVoucher CRSVoucher1 { get; set; }
        public virtual CRSVoucher CRSVoucher2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRSVoucherDetail> CRSVoucherDetails { get; set; }
    }
}
