//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curriculum_Subject
    {
        public int Curriculum_SubjectID { get; set; }
        public int CurriculumID { get; set; }
        public int SubjectID { get; set; }
        public byte YearLevel { get; set; }
        public byte Semester { get; set; }
        public Nullable<bool> Needs83 { get; set; }
        public Nullable<bool> ForQualifyingExam { get; set; }
    
        public virtual Curriculum Curriculum { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
