//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerSurveyDetail
    {
        public int SurveyDetailID { get; set; }
        public int QuestionID { get; set; }
        public Nullable<int> AnswerID { get; set; }
        public int SurveyID { get; set; }
    
        public virtual CustomerSurvey CustomerSurvey { get; set; }
        public virtual CustomerSurveyQuestion CustomerSurveyQuestion { get; set; }
    }
}
