//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeWork
    {
        public int EmployeeWorkID { get; set; }
        public Nullable<bool> InLetran { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string Company { get; set; }
        public string CompanyAddress { get; set; }
        public string CompanyZipCode { get; set; }
        public Nullable<int> EmployeeStatusID { get; set; }
        public string WorkType { get; set; }
        public string WorkPosition { get; set; }
        public string WorkLevel { get; set; }
        public string WorkRank { get; set; }
        public string Salary { get; set; }
        public string StartMont { get; set; }
        public string StartYear { get; set; }
        public string EndMonth { get; set; }
        public string EndYear { get; set; }
        public string ContractStartDate { get; set; }
        public string ContractEndDate { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string ReasonLeaving { get; set; }
        public Nullable<bool> Validate { get; set; }
        public string CompanyCity { get; set; }
        public string WorkDept { get; set; }
        public string InclusiveDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual EmployeeStatu EmployeeStatu { get; set; }
    }
}
