//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeHistory
    {
        public int EmployeeHistoryID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> EmployeePositionID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Remark { get; set; }
    
        public virtual AcademicDepartment AcademicDepartment { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual EmployeePosition EmployeePosition { get; set; }
    }
}
