//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSeminar
    {
        public int EmployeeSeminarID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string Title { get; set; }
        public string Sponsor { get; set; }
        public string Venue { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string InclusiveDate { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
