//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeEducation
    {
        public int EmployeeEducationID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string EducationType { get; set; }
        public string Institution { get; set; }
        public string InstitutionAddress { get; set; }
        public string InstitutionCity { get; set; }
        public string InstitutionState { get; set; }
        public string InstitutionCountry { get; set; }
        public string Degree { get; set; }
        public string Major { get; set; }
        public string Minor { get; set; }
        public string GraduationDate { get; set; }
        public string SONumber { get; set; }
        public string ThesisTitle { get; set; }
        public Nullable<bool> ThesisDefended { get; set; }
        public Nullable<bool> AcademicsCompleted { get; set; }
        public Nullable<bool> ComprehensiveExam { get; set; }
        public string Units { get; set; }
        public string StartMonth { get; set; }
        public string StartYear { get; set; }
        public string EndMonth { get; set; }
        public string EndYear { get; set; }
        public string Awards { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
