//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.EmployeeEducations = new HashSet<EmployeeEducation>();
            this.EmployeeFeedbacks = new HashSet<EmployeeFeedback>();
            this.EmployeeSeminars = new HashSet<EmployeeSeminar>();
            this.EmployeeWorks = new HashSet<EmployeeWork>();
            this.Faculties = new HashSet<Faculty>();
            this.GuidanceReferrals = new HashSet<GuidanceReferral>();
            this.GuidanceReferrals1 = new HashSet<GuidanceReferral>();
            this.HRISChangeVacationLeaves = new HashSet<HRISChangeVacationLeave>();
            this.HRISMakeUpClasses = new HashSet<HRISMakeUpClass>();
            this.HRISNoticeofAbsences = new HashSet<HRISNoticeofAbsence>();
            this.HRISOvertimes = new HashSet<HRISOvertime>();
            this.HRISPostTrainings = new HashSet<HRISPostTraining>();
            this.HRISSubstituteClasses = new HashSet<HRISSubstituteClass>();
            this.HRISSubstituteClasses1 = new HashSet<HRISSubstituteClass>();
            this.LeaveBalances = new HashSet<LeaveBalance>();
            this.Leaves = new HashSet<Leave>();
            this.EmployeeHistories = new HashSet<EmployeeHistory>();
            this.HRISOffCampusActivities = new HashSet<HRISOffCampusActivity>();
        }
    
        public int EmployeeID { get; set; }
        public string EmployeeNo { get; set; }
        public string Title { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string Nickname { get; set; }
        public Nullable<int> EmployeeDepartmentID { get; set; }
        public Nullable<int> FacultyAreaID { get; set; }
        public Nullable<int> EmployeeStatusID { get; set; }
        public Nullable<int> EmployeeDesignation { get; set; }
        public Nullable<int> EmployeePositionID { get; set; }
        public Nullable<int> EmployeeLevelID { get; set; }
        public Nullable<System.DateTime> DateHired { get; set; }
        public Nullable<System.DateTime> DatePermanency { get; set; }
        public Nullable<System.DateTime> DateEndContract { get; set; }
        public string ReasonForLeaving { get; set; }
        public string OtherReasonForLeaving { get; set; }
        public Nullable<System.DateTime> DateResigned { get; set; }
        public Nullable<System.DateTime> DateRetired { get; set; }
        public string ResidentialAddress { get; set; }
        public Nullable<int> ResidentialAreaID { get; set; }
        public Nullable<int> ResidentialZipCodeID { get; set; }
        public string ProvincialAddress { get; set; }
        public Nullable<int> ProvincialAreaID { get; set; }
        public Nullable<int> ProvincialZipCodeID { get; set; }
        public string TelephoneNo { get; set; }
        public string ProvincialTelephoneNo { get; set; }
        public string MobileNo { get; set; }
        public string PrimaryEmail { get; set; }
        public string SecondaryEmail { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Birthplace { get; set; }
        public string CivilStatus { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string Spouse { get; set; }
        public string SpouseOccupation { get; set; }
        public Nullable<int> Children { get; set; }
        public string Child1 { get; set; }
        public string Child2 { get; set; }
        public string Child3 { get; set; }
        public string Child4 { get; set; }
        public string Child5 { get; set; }
        public string OtherChild { get; set; }
        public string Nationality { get; set; }
        public string Religion { get; set; }
        public string TaxStatus { get; set; }
        public string TIN { get; set; }
        public string SSS { get; set; }
        public string PAG_IBIG { get; set; }
        public string PhilHealth { get; set; }
        public string CedulaNo { get; set; }
        public string CedulaDate { get; set; }
        public string CedulaPlace { get; set; }
        public Nullable<System.DateTime> DateEncoded { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<bool> Archive { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<int> NewDeptID { get; set; }
        public byte[] pic { get; set; }
        public Nullable<int> bioid { get; set; }
        public string IDCode { get; set; }
        public string IDCode2 { get; set; }
        public string NameSuffix { get; set; }
        public Nullable<int> EmployeeScheduleId { get; set; }
        public Nullable<int> EmploymentTypeID { get; set; }
        public string BankAccountNo { get; set; }
    
        public virtual AcademicDepartment AcademicDepartment { get; set; }
        public virtual Area Area { get; set; }
        public virtual Area Area1 { get; set; }
        public virtual Zipcode Zipcode { get; set; }
        public virtual EmployeeDesignation EmployeeDesignation1 { get; set; }
        public virtual EmployeeLevel EmployeeLevel { get; set; }
        public virtual EmployeePosition EmployeePosition { get; set; }
        public virtual EmployeeStatu EmployeeStatu { get; set; }
        public virtual FacultyArea FacultyArea { get; set; }
        public virtual Zipcode Zipcode1 { get; set; }
        public virtual Zipcode Zipcode2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeEducation> EmployeeEducations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeFeedback> EmployeeFeedbacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeSeminar> EmployeeSeminars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeWork> EmployeeWorks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Faculty> Faculties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GuidanceReferral> GuidanceReferrals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GuidanceReferral> GuidanceReferrals1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRISChangeVacationLeave> HRISChangeVacationLeaves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRISMakeUpClass> HRISMakeUpClasses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRISNoticeofAbsence> HRISNoticeofAbsences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRISOvertime> HRISOvertimes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRISPostTraining> HRISPostTrainings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRISSubstituteClass> HRISSubstituteClasses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRISSubstituteClass> HRISSubstituteClasses1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveBalance> LeaveBalances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leave> Leaves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeHistory> EmployeeHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRISOffCampusActivity> HRISOffCampusActivities { get; set; }
    }
}
