//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnlistmentDate
    {
        public int EnlistmentDateID { get; set; }
        public Nullable<System.DateTime> EnlistmentStart { get; set; }
        public Nullable<System.DateTime> EnlistmentEnd { get; set; }
        public Nullable<System.DateTime> AdjustmentStart { get; set; }
        public Nullable<System.DateTime> AdjustmentEnd { get; set; }
        public int PeriodID { get; set; }
    
        public virtual Period Period { get; set; }
    }
}
