//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnlistmentSystemParameter
    {
        public int EnlistmentSystemParameterID { get; set; }
        public Nullable<int> PeriodID { get; set; }
        public Nullable<int> TermID { get; set; }
        public Nullable<int> ProgramID { get; set; }
        public Nullable<int> EducLevelID { get; set; }
        public Nullable<System.DateTime> SEnlistment { get; set; }
        public Nullable<System.DateTime> EEnlistment { get; set; }
    
        public virtual EducationalLevel EducationalLevel { get; set; }
        public virtual Period Period { get; set; }
        public virtual Progam Progam { get; set; }
    }
}
