//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacultyLoadingDisclosure
    {
        public int FacultyLoadingDisclosureRequirementID { get; set; }
        public string Institution { get; set; }
        public string Days { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public int FacultyLoadingID { get; set; }
    
        public virtual FacultyLoading FacultyLoading { get; set; }
    }
}
