//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GJVoucher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GJVoucher()
        {
            this.GJVoucherDetails = new HashSet<GJVoucherDetail>();
        }
    
        public int GJVoucherID { get; set; }
        public System.DateTime GJVoucherDate { get; set; }
        public string GJVoucherNo { get; set; }
        public string Particulars { get; set; }
        public int SchoolYearID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GJVoucherDetail> GJVoucherDetails { get; set; }
        public virtual SchoolYear SchoolYear { get; set; }
    }
}
