//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GraduationApplication
    {
        public int GradAppStudentID { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Birthplace { get; set; }
        public string Parent_Guardian { get; set; }
        public string Parent_Occupation { get; set; }
        public string ParentAddress { get; set; }
        public string PrimaryCourseSchool { get; set; }
        public string PrimaryCourseSchoolAddress { get; set; }
        public string PrimaryCourseYear { get; set; }
        public string IntermediateCourseSchool { get; set; }
        public string IntermediateCourseSchoolAddress { get; set; }
        public string IntermediateCourseYear { get; set; }
        public string HighSchool1 { get; set; }
        public string HighSchool1Comp { get; set; }
        public string HighSchool2 { get; set; }
        public string HighSchool2Comp { get; set; }
        public string HighSchool3 { get; set; }
        public string HighSchool3Comp { get; set; }
        public string HighSchool4 { get; set; }
        public string HighSchool4Comp { get; set; }
        public string CollegeDegree { get; set; }
        public string CollegeName { get; set; }
        public Nullable<System.DateTime> GraduationDate { get; set; }
        public Nullable<System.DateTime> SubmissionDate { get; set; }
        public Nullable<bool> JoiningCeremony { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Major { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string Remarks { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string Degree1 { get; set; }
        public string Degree1School { get; set; }
        public string Degree2 { get; set; }
        public string Degree2School { get; set; }
        public string ComprehensiveExam { get; set; }
        public string OralExam { get; set; }
        public string ThesisTitle { get; set; }
        public string UpperRemarks { get; set; }
        public string AwardsRecieved { get; set; }
        public string Course { get; set; }
        public string TORRemarks { get; set; }
        public Nullable<bool> ApplicationForm { get; set; }
        public Nullable<bool> Form138 { get; set; }
        public Nullable<bool> Form137 { get; set; }
        public Nullable<bool> TOR { get; set; }
        public Nullable<bool> Diploma { get; set; }
        public Nullable<bool> GoodMoral { get; set; }
        public Nullable<bool> HonorableDismissal { get; set; }
        public Nullable<bool> BirthCertificate { get; set; }
        public Nullable<bool> LetranHonorable { get; set; }
        public Nullable<bool> LetranIssuedTOR { get; set; }
        public Nullable<bool> LetranIssuedDiploma { get; set; }
        public string ApplicationFormRemarks { get; set; }
        public string Form138Remarks { get; set; }
        public string Form137Remarks { get; set; }
        public string TORInstruction { get; set; }
        public string DiplomaRemarks { get; set; }
        public string GoodMoralRemarks { get; set; }
        public string HonorableDismissalRemarks { get; set; }
        public string BirthCertificateRemarks { get; set; }
        public string LetranDismissalRemarks { get; set; }
        public string LetranIssuedTORRemarks { get; set; }
        public string LetranIssuedDiplomaRemarks { get; set; }
        public string TOROtherRemars { get; set; }
        public string PAASCURemarks { get; set; }
        public string CHEDSORemark { get; set; }
        public string Form137RemarksSHS { get; set; }
    }
}
