//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradeElemOld
    {
        public int GradeElemOldID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<int> PeriodID { get; set; }
        public Nullable<double> Quarter1 { get; set; }
        public Nullable<double> Quarter2 { get; set; }
        public Nullable<double> Quarter3 { get; set; }
        public Nullable<double> Quarter4 { get; set; }
        public Nullable<double> Average { get; set; }
        public Nullable<double> Conduct { get; set; }
        public Nullable<int> Spirituality { get; set; }
        public Nullable<int> Patriotism { get; set; }
        public Nullable<int> Letranism { get; set; }
        public Nullable<int> DaysPresent { get; set; }
        public Nullable<int> SchoolDaysQuarterID { get; set; }
        public Nullable<int> GradeYear { get; set; }
        public string Section { get; set; }
    }
}
