//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradeKinderQuestionSubject
    {
        public int GradeKinderQuestionSubjectID { get; set; }
        public Nullable<int> GradeKinderQuestionID { get; set; }
        public Nullable<int> SubjectID { get; set; }
    
        public virtual GradeKinderQuestion GradeKinderQuestion { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
