//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradeElementary
    {
        public int GradeElementaryID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public string GradeLevel { get; set; }
        public Nullable<double> Quarter1 { get; set; }
        public Nullable<double> Quarter2 { get; set; }
        public Nullable<double> Quarter3 { get; set; }
        public Nullable<double> Quarter4 { get; set; }
        public Nullable<double> Average { get; set; }
        public Nullable<double> ComputedAverage { get; set; }
        public Nullable<double> Conduct1 { get; set; }
        public Nullable<double> Conduct2 { get; set; }
        public Nullable<double> Conduct3 { get; set; }
        public Nullable<double> Conduct4 { get; set; }
        public Nullable<double> Prefect1 { get; set; }
        public Nullable<double> Prefect2 { get; set; }
        public Nullable<double> Prefect3 { get; set; }
        public Nullable<double> Prefect4 { get; set; }
        public Nullable<int> PeriodID { get; set; }
        public string SectionName { get; set; }
        public Nullable<int> FacultyID { get; set; }
    
        public virtual Subject Subject { get; set; }
        public virtual Period Period { get; set; }
        public virtual Student Student { get; set; }
    }
}
