//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradeKinderRemark
    {
        public int GraderKinderRemarksID { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string Remark3 { get; set; }
        public string Remark4 { get; set; }
        public Nullable<int> PeriodID { get; set; }
        public Nullable<int> StudentID { get; set; }
    
        public virtual Period Period { get; set; }
        public virtual Student Student { get; set; }
    }
}
