//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradeKinder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GradeKinder()
        {
            this.GradeKinderDetails = new HashSet<GradeKinderDetail>();
        }
    
        public int GradeKinderID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> PeriodID { get; set; }
        public Nullable<System.DateTime> DateEncoded { get; set; }
        public string EncodedBy { get; set; }
        public Nullable<int> FacultyID { get; set; }
    
        public virtual Faculty Faculty { get; set; }
        public virtual Period Period { get; set; }
        public virtual Student Student { get; set; }
        public virtual Subject Subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GradeKinderDetail> GradeKinderDetails { get; set; }
    }
}
