//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradeKinderDetail
    {
        public int GradeKinderDetailsID { get; set; }
        public Nullable<int> GradeKinderID { get; set; }
        public Nullable<int> GradeKinderQuestionID { get; set; }
        public string Quarter1 { get; set; }
        public string Quarter2 { get; set; }
        public string Quarter3 { get; set; }
        public string Quarter4 { get; set; }
    
        public virtual GradeKinder GradeKinder { get; set; }
        public virtual GradeKinderQuestion GradeKinderQuestion { get; set; }
    }
}
