//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuidanceSurveyDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GuidanceSurveyDetail()
        {
            this.GuidanceSurveyAnswerDetails = new HashSet<GuidanceSurveyAnswerDetail>();
        }
    
        public int GuidanceSurveyDetailsID { get; set; }
        public Nullable<int> GuidanceSurveyQuestionID { get; set; }
        public Nullable<int> GuidanceSurveyID { get; set; }
    
        public virtual GuidanceSurvey GuidanceSurvey { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GuidanceSurveyAnswerDetail> GuidanceSurveyAnswerDetails { get; set; }
        public virtual GuidanceSurveyQuestion GuidanceSurveyQuestion { get; set; }
    }
}
