//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuidanceSeminar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GuidanceSeminar()
        {
            this.GuidanceStudentSeminars = new HashSet<GuidanceStudentSeminar>();
        }
    
        public int SeminarID { get; set; }
        public string SeminarName { get; set; }
        public Nullable<System.DateTime> SeminarDate { get; set; }
        public Nullable<int> PeriodID { get; set; }
        public string Venue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GuidanceStudentSeminar> GuidanceStudentSeminars { get; set; }
    }
}
