//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuidanceStudentInfo
    {
        public int StudentID { get; set; }
        public Nullable<int> StudentType { get; set; }
        public Nullable<int> StudentCategory { get; set; }
        public string LanguagesSpoken { get; set; }
        public string FatherNationality { get; set; }
        public string FatherAge { get; set; }
        public string FatherReligion { get; set; }
        public string FatherLife { get; set; }
        public string FatherAddress { get; set; }
        public string FatherEmployerAddress { get; set; }
        public string FatherEmployerEmail { get; set; }
        public string FatherEmployerTelNo { get; set; }
        public string MotherNationality { get; set; }
        public string MotherAge { get; set; }
        public string MotherReligion { get; set; }
        public string MotherLife { get; set; }
        public string MotherAddress { get; set; }
        public string MotherEmployerAddress { get; set; }
        public string MotherEmployerEmail { get; set; }
        public string MotherEmployerTelNo { get; set; }
        public string LivingWith { get; set; }
        public string FamilyTradition { get; set; }
        public string ChildhoodExperience { get; set; }
        public string SaddestChildhoodExperience { get; set; }
        public string PresentHealthCondition { get; set; }
        public string ChildhoodDisorders { get; set; }
        public string PhysicalConcerns { get; set; }
        public Nullable<bool> PsychologicalTreatment { get; set; }
        public string PyschologicalReason { get; set; }
        public string PyschologicalDetails { get; set; }
        public string MedicationList { get; set; }
        public string ElementarySchool { get; set; }
        public string ElementaryAwards { get; set; }
        public string HighSchool { get; set; }
        public string HighSchoolAwards { get; set; }
        public string College { get; set; }
        public string CollegeAwards { get; set; }
        public string Vocational { get; set; }
        public string VocationalAwards { get; set; }
        public string ImmediateFamilyProblem { get; set; }
        public string ProblemSenses { get; set; }
        public string SubjectMost { get; set; }
        public string SubjectLeast { get; set; }
        public string Hobbies { get; set; }
        public string Organization { get; set; }
        public string Ambitions { get; set; }
        public string DescriptionSelf { get; set; }
        public string BriefIssue { get; set; }
        public string Disruptive { get; set; }
        public Nullable<System.DateTime> DateSubmitted { get; set; }
        public string PresentAddress { get; set; }
        public string PermanentAddress { get; set; }
        public string PresentAddressTel { get; set; }
        public string PermanentAddressTel { get; set; }
        public string Jobs180ResumeLink { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
