//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuidanceReferral
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GuidanceReferral()
        {
            this.GuidanceReferralReasonAnswers = new HashSet<GuidanceReferralReasonAnswer>();
        }
    
        public int GuidanceReferralID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<System.DateTime> ReferralDate { get; set; }
        public string Background { get; set; }
        public Nullable<System.DateTime> ReplyReferralDate { get; set; }
        public Nullable<System.DateTime> DateReported { get; set; }
        public Nullable<int> GuidanceEmployeeID { get; set; }
        public Nullable<int> StatusID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Student Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GuidanceReferralReasonAnswer> GuidanceReferralReasonAnswers { get; set; }
    }
}
