//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuidanceSurveyAnswer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GuidanceSurveyAnswer()
        {
            this.GuidanceSurveyAnswerConcerns = new HashSet<GuidanceSurveyAnswerConcern>();
            this.GuidanceSurveyAnswerDetails = new HashSet<GuidanceSurveyAnswerDetail>();
        }
    
        public int GuidanceSurveyAnswerID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Comment { get; set; }
        public Nullable<int> GuidanceSurveyID { get; set; }
        public Nullable<int> PeriodID { get; set; }
        public string ImmediatePlan { get; set; }
        public string Envision { get; set; }
        public Nullable<bool> LetranRecommendation { get; set; }
        public string LetranRecommendationReason { get; set; }
        public string SuggestionsGCC { get; set; }
        public string SuggestionsLetran { get; set; }
        public string MockInterviewComment { get; set; }
        public Nullable<System.DateTime> SurveyDate { get; set; }
        public string AreaOfConcern { get; set; }
    
        public virtual Period Period { get; set; }
        public virtual Student Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GuidanceSurveyAnswerConcern> GuidanceSurveyAnswerConcerns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GuidanceSurveyAnswerDetail> GuidanceSurveyAnswerDetails { get; set; }
    }
}
