//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuidanceOtherPeople
    {
        public int OtherID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string OthersName { get; set; }
        public string OthersAge { get; set; }
        public string OthersGender { get; set; }
        public string OthersRelationship { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
