//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuidanceImportantPerson
    {
        public int ImportantID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string ImportantName { get; set; }
        public string ImportantAge { get; set; }
        public string ImportantGender { get; set; }
        public string ImportantOccupation { get; set; }
        public string ImportantContact { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
