//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuidanceSurveyAnswerDetail
    {
        public int GuidanceSurveyAnswerDetailID { get; set; }
        public Nullable<int> GuidanceSurveyAnswerID { get; set; }
        public Nullable<int> GuidanceSurveyDetailsID { get; set; }
        public string Answer { get; set; }
    
        public virtual GuidanceSurveyAnswer GuidanceSurveyAnswer { get; set; }
        public virtual GuidanceSurveyDetail GuidanceSurveyDetail { get; set; }
    }
}
