//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuidanceSibling
    {
        public int SiblingID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string SiblingName { get; set; }
        public string SiblingAge { get; set; }
        public string SiblingGender { get; set; }
        public string SiblingSchoolOffice { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
