//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRISOnlineJobApplication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HRISOnlineJobApplication()
        {
            this.HRISOnlineJobApplicationEducations = new HashSet<HRISOnlineJobApplicationEducation>();
            this.HRISOnlineJobApplicationLicenses = new HashSet<HRISOnlineJobApplicationLicens>();
            this.HRISOnlineJobApplicationSeminars = new HashSet<HRISOnlineJobApplicationSeminar>();
            this.HRISOnlineJobApplicationWorkExperiences = new HashSet<HRISOnlineJobApplicationWorkExperience>();
        }
    
        public int ApplicationID { get; set; }
        public Nullable<int> EmployeeJobID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string CityAddress { get; set; }
        public string TelephoneNo { get; set; }
        public string MobileNo { get; set; }
        public string ProvincialAddress { get; set; }
        public string Age { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Birthplace { get; set; }
        public string CivilStatus { get; set; }
        public string Citizenship { get; set; }
        public string Religion { get; set; }
        public string TIN { get; set; }
        public string SSS { get; set; }
        public string PAGIBIG { get; set; }
        public string PHILHEALTH { get; set; }
        public string SpecialSkills { get; set; }
        public string LanguagesSpeak { get; set; }
        public string MachinesOperate { get; set; }
        public string AdditionalKnowledge { get; set; }
        public string PhyschologicalImpairments { get; set; }
        public Nullable<bool> Impairments { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<int> ApplicationStatusID { get; set; }
    
        public virtual EmployeeJob EmployeeJob { get; set; }
        public virtual HRISOnlineJobApplicationStatu HRISOnlineJobApplicationStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRISOnlineJobApplicationEducation> HRISOnlineJobApplicationEducations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRISOnlineJobApplicationLicens> HRISOnlineJobApplicationLicenses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRISOnlineJobApplicationSeminar> HRISOnlineJobApplicationSeminars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRISOnlineJobApplicationWorkExperience> HRISOnlineJobApplicationWorkExperiences { get; set; }
    }
}
