//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRISMakeUpClassDetail
    {
        public int MakeUpClassDetailsID { get; set; }
        public Nullable<int> MakeUpClassID { get; set; }
        public Nullable<System.DateTime> DateOfAbsence { get; set; }
        public Nullable<int> ScheduleID { get; set; }
        public Nullable<System.DateTime> DateOfMakeUpClass { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<int> MakeUpClassRoomID { get; set; }
    
        public virtual HRISMakeUpClass HRISMakeUpClass { get; set; }
        public virtual Room Room { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
