//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRISEmployeeSchedule
    {
        public int EmployeeScheduleId { get; set; }
        public string EmployeeNumber { get; set; }
        public string ShiftCode { get; set; }
    
        public virtual HRISShift HRISShift { get; set; }
    }
}
