//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRISOvertimeDetail
    {
        public int EmployeeOvertimeDetailsID { get; set; }
        public Nullable<int> EmployeeOvertimeID { get; set; }
        public System.DateTime Date { get; set; }
        public string CalendarDay { get; set; }
        public string Reason { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
    
        public virtual HRISOvertime HRISOvertime { get; set; }
    }
}
