//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRISEmployeesShift
    {
        public int EmployeeShiftID { get; set; }
        public string EmployeeShiftCode { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string DayName { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public Nullable<int> DayID { get; set; }
        public Nullable<bool> IsNoBreak_ { get; set; }
    }
}
