//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRISApplicationCertificateEmployment
    {
        public int CetificateEmploymentID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public int DepartmentID { get; set; }
        public string Sendee { get; set; }
        public string SendeeAddress { get; set; }
        public System.DateTime DateFile { get; set; }
        public System.DateTime DateNeeded { get; set; }
        public string Purpose { get; set; }
    
        public virtual AcademicDepartment AcademicDepartment { get; set; }
    }
}
