//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRISOnlineJobApplicationLicens
    {
        public int ApplicationLicenseID { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public string ExamPassed { get; set; }
        public Nullable<System.DateTime> ExamDate { get; set; }
        public string Rating { get; set; }
        public string ExamPlace { get; set; }
    
        public virtual HRISOnlineJobApplication HRISOnlineJobApplication { get; set; }
    }
}
