//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRISChangeVacationLeaveDetail
    {
        public int VacationLeaveChangeDetailsID { get; set; }
        public Nullable<int> LeaveID { get; set; }
        public Nullable<System.DateTime> NewDateStart { get; set; }
        public Nullable<System.DateTime> NewDateEnd { get; set; }
        public string Reason { get; set; }
        public Nullable<int> VacationLeaveChangeID { get; set; }
    
        public virtual HRISChangeVacationLeave HRISChangeVacationLeave { get; set; }
        public virtual Leave Leave { get; set; }
    }
}
