//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRISOnlineJobApplicationEducation
    {
        public int ApplicationEducationID { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public Nullable<int> EducationType { get; set; }
        public string SchoolAddress { get; set; }
        public string Course { get; set; }
        public string InclusiveDates { get; set; }
        public string Honors { get; set; }
    
        public virtual HRISOnlineJobApplication HRISOnlineJobApplication { get; set; }
    }
}
