//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRISPostTraining
    {
        public int PostTrainingID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string Titile { get; set; }
        public string DateStart { get; set; }
        public string DateEnd { get; set; }
        public string Venue { get; set; }
        public Nullable<int> HRISActivityTypeID { get; set; }
        public string Others { get; set; }
        public string Background { get; set; }
        public string Expectation { get; set; }
        public string ResourcePerson { get; set; }
        public string Approach { get; set; }
        public string KeyLearning { get; set; }
        public string Issues { get; set; }
        public string Generalization { get; set; }
        public Nullable<System.DateTime> DateFile { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual HRISActivityType HRISActivityType { get; set; }
    }
}
