//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class intranet_leave_tran
    {
        public long lvID { get; set; }
        public string empno { get; set; }
        public string lvtype { get; set; }
        public Nullable<decimal> days { get; set; }
        public Nullable<System.DateTime> frdate { get; set; }
        public Nullable<System.DateTime> todate { get; set; }
        public Nullable<System.DateTime> filedate { get; set; }
        public string filedby { get; set; }
        public string sreason { get; set; }
        public string reason { get; set; }
        public string app_status { get; set; }
        public Nullable<System.DateTime> app_date { get; set; }
        public Nullable<bool> printstatus { get; set; }
        public Nullable<System.DateTime> printdate { get; set; }
        public Nullable<System.DateTime> canceldate { get; set; }
        public string appby { get; set; }
        public string ip { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> LeaveTypeID { get; set; }
        public Nullable<int> SickLeaveReasonID { get; set; }
        public Nullable<int> LeaveApprovedStatusID { get; set; }
        public Nullable<int> FiledByID { get; set; }
        public Nullable<int> ApprovedByID { get; set; }
    }
}
