//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalVoucher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JournalVoucher()
        {
            this.JVDetails = new HashSet<JVDetail>();
        }
    
        public int JVID { get; set; }
        public string JVNo { get; set; }
        public System.DateTime Date { get; set; }
        public int AccountingBookID { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> DepartmentID { get; set; }
    
        public virtual AccountingBook AccountingBook { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JVDetail> JVDetails { get; set; }
    }
}
