//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEAf
    {
        public string USERNAME { get; set; }
        public string EMPN { get; set; }
        public System.DateTime DATE_FROM { get; set; }
        public System.DateTime DATE_TO { get; set; }
        public Nullable<System.DateTime> TIME_FROM { get; set; }
        public Nullable<System.DateTime> TIME_TO { get; set; }
        public string CODE { get; set; }
        public int TYPE { get; set; }
        public Nullable<System.DateTime> ENTRYDATE { get; set; }
        public Nullable<double> CREDITS { get; set; }
    }
}
