//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveBalance
    {
        public int LeaveBalanceID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<decimal> SickLeaveBalance { get; set; }
        public Nullable<decimal> VacationLeaveBalance { get; set; }
        public Nullable<decimal> ServiceIncentiveLeave { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
