//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveCredit
    {
        public int LeaveCreditID { get; set; }
        public Nullable<System.DateTime> DateOccured { get; set; }
        public byte[] LogTimeStamp { get; set; }
    }
}
