//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int LogID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string IPAddress { get; set; }
        public string ComputerName { get; set; }
        public string Details { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public byte[] LogTimestamp { get; set; }
        public Nullable<int> PeriodID { get; set; }
    }
}
