//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Miscellaneou
    {
        public int FeeID { get; set; }
        public string Description { get; set; }
        public double Amount { get; set; }
        public Nullable<bool> NewStatus { get; set; }
        public bool DiscountCharge { get; set; }
        public Nullable<int> EducationalLevel { get; set; }
        public Nullable<int> YearLevel { get; set; }
        public Nullable<int> ExceptCurrID { get; set; }
        public Nullable<int> OnlyCurrID { get; set; }
    
        public virtual EducationalLevel EducationalLevel1 { get; set; }
        public virtual Fee Fee { get; set; }
    }
}
