//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LetranIntegratedSystemEntities : DbContext
    {
        public LetranIntegratedSystemEntities()
            : base("name=LetranIntegratedSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AcademicArea> AcademicAreas { get; set; }
        public virtual DbSet<AcademicAreaHead> AcademicAreaHeads { get; set; }
        public virtual DbSet<AcademicDepartment> AcademicDepartments { get; set; }
        public virtual DbSet<AcademicDepartmentHead> AcademicDepartmentHeads { get; set; }
        public virtual DbSet<AccountingBook> AccountingBooks { get; set; }
        public virtual DbSet<Action> Actions { get; set; }
        public virtual DbSet<Adjustment> Adjustments { get; set; }
        public virtual DbSet<AdjustmentDetailFee> AdjustmentDetailFees { get; set; }
        public virtual DbSet<AdjustmentDetail> AdjustmentDetails { get; set; }
        public virtual DbSet<AdmissionExamDate> AdmissionExamDates { get; set; }
        public virtual DbSet<AdmissionExamResult> AdmissionExamResults { get; set; }
        public virtual DbSet<AdmissionExamResultType> AdmissionExamResultTypes { get; set; }
        public virtual DbSet<AdmissionMarketingEffortsCareerFair> AdmissionMarketingEffortsCareerFairs { get; set; }
        public virtual DbSet<AdmissionMarketingEffortsCareerTalk> AdmissionMarketingEffortsCareerTalks { get; set; }
        public virtual DbSet<AdmissionMarketingEffortsMaterial> AdmissionMarketingEffortsMaterials { get; set; }
        public virtual DbSet<AdmissionMarketingEffortsSchool> AdmissionMarketingEffortsSchools { get; set; }
        public virtual DbSet<Aircon> Aircons { get; set; }
        public virtual DbSet<Annoucement_Table> Annoucement_Table { get; set; }
        public virtual DbSet<ApplicationEncourageDetail> ApplicationEncourageDetails { get; set; }
        public virtual DbSet<ApplicationEncourageQuestion> ApplicationEncourageQuestions { get; set; }
        public virtual DbSet<ApplicationPlanDetail> ApplicationPlanDetails { get; set; }
        public virtual DbSet<ApplicationPlanQuestion> ApplicationPlanQuestions { get; set; }
        public virtual DbSet<ApplicationSurveyDetail> ApplicationSurveyDetails { get; set; }
        public virtual DbSet<ApplicationSurveyQuestion> ApplicationSurveyQuestions { get; set; }
        public virtual DbSet<APVoucher> APVouchers { get; set; }
        public virtual DbSet<APVoucherDetail> APVoucherDetails { get; set; }
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<ARMessage> ARMessages { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Assessment> Assessments { get; set; }
        public virtual DbSet<AttendanceElementary> AttendanceElementaries { get; set; }
        public virtual DbSet<AttendanceKinder> AttendanceKinders { get; set; }
        public virtual DbSet<AttendanceSH> AttendanceSHS { get; set; }
        public virtual DbSet<BackAccount> BackAccounts { get; set; }
        public virtual DbSet<BackAccountPayment> BackAccountPayments { get; set; }
        public virtual DbSet<BalanceDueOverride> BalanceDueOverrides { get; set; }
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<Bank_Account> Bank_Account { get; set; }
        public virtual DbSet<BankTransaction> BankTransactions { get; set; }
        public virtual DbSet<BasicEducationOther> BasicEducationOthers { get; set; }
        public virtual DbSet<bdorefno> bdorefnoes { get; set; }
        public virtual DbSet<CancelledOR> CancelledORs { get; set; }
        public virtual DbSet<CashierDCR> CashierDCRs { get; set; }
        public virtual DbSet<CashierDCRDetail> CashierDCRDetails { get; set; }
        public virtual DbSet<CashierDCRVoid> CashierDCRVoids { get; set; }
        public virtual DbSet<CategoryNewsTable> CategoryNewsTables { get; set; }
        public virtual DbSet<CDSVoucher> CDSVouchers { get; set; }
        public virtual DbSet<CDSVoucherDetail> CDSVoucherDetails { get; set; }
        public virtual DbSet<ChangeOfGrade> ChangeOfGrades { get; set; }
        public virtual DbSet<ChangeOfGradeDoctoral> ChangeOfGradeDoctorals { get; set; }
        public virtual DbSet<ChangeOfGradeMasteral> ChangeOfGradeMasterals { get; set; }
        public virtual DbSet<ChartOfAccount> ChartOfAccounts { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<ClubJH> ClubJHS { get; set; }
        public virtual DbSet<CoaBank> CoaBanks { get; set; }
        public virtual DbSet<COAccountType> COAccountTypes { get; set; }
        public virtual DbSet<CounselingRecord> CounselingRecords { get; set; }
        public virtual DbSet<CreditCardPayment> CreditCardPayments { get; set; }
        public virtual DbSet<CRSVoucher> CRSVouchers { get; set; }
        public virtual DbSet<CRSVoucherDetail> CRSVoucherDetails { get; set; }
        public virtual DbSet<Curriculum> Curricula { get; set; }
        public virtual DbSet<Curriculum_Subject> Curriculum_Subject { get; set; }
        public virtual DbSet<CustomerSurvey> CustomerSurveys { get; set; }
        public virtual DbSet<CustomerSurveyDetail> CustomerSurveyDetails { get; set; }
        public virtual DbSet<CustomerSurveyQuestion> CustomerSurveyQuestions { get; set; }
        public virtual DbSet<Discount> Discounts { get; set; }
        public virtual DbSet<DiscountCategory> DiscountCategories { get; set; }
        public virtual DbSet<DiscountType> DiscountTypes { get; set; }
        public virtual DbSet<DMCM> DMCMs { get; set; }
        public virtual DbSet<EducationalLevel> EducationalLevels { get; set; }
        public virtual DbSet<EducationalLevel4> EducationalLevel4 { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeeAnnouncement> EmployeeAnnouncements { get; set; }
        public virtual DbSet<EmployeeDepartment> EmployeeDepartments { get; set; }
        public virtual DbSet<EmployeeDesignation> EmployeeDesignations { get; set; }
        public virtual DbSet<EmployeeDivision> EmployeeDivisions { get; set; }
        public virtual DbSet<EmployeeEducation> EmployeeEducations { get; set; }
        public virtual DbSet<EmployeeFeedback> EmployeeFeedbacks { get; set; }
        public virtual DbSet<EmployeeJob> EmployeeJobs { get; set; }
        public virtual DbSet<EmployeeLevel> EmployeeLevels { get; set; }
        public virtual DbSet<EmployeePosition> EmployeePositions { get; set; }
        public virtual DbSet<EmployeeRank> EmployeeRanks { get; set; }
        public virtual DbSet<EmployeeSeminar> EmployeeSeminars { get; set; }
        public virtual DbSet<EmployeeStatu> EmployeeStatus { get; set; }
        public virtual DbSet<EmployeeWork> EmployeeWorks { get; set; }
        public virtual DbSet<EnlistmentDate> EnlistmentDates { get; set; }
        public virtual DbSet<EnlistmentSystemParameter> EnlistmentSystemParameters { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<EventSubject> EventSubjects { get; set; }
        public virtual DbSet<EventType> EventTypes { get; set; }
        public virtual DbSet<FacilityType> FacilityTypes { get; set; }
        public virtual DbSet<Faculty> Faculties { get; set; }
        public virtual DbSet<FacultyArea> FacultyAreas { get; set; }
        public virtual DbSet<FacultyLoading> FacultyLoadings { get; set; }
        public virtual DbSet<FacultyLoadingDisclosure> FacultyLoadingDisclosures { get; set; }
        public virtual DbSet<Fee> Fees { get; set; }
        public virtual DbSet<GJVoucher> GJVouchers { get; set; }
        public virtual DbSet<GJVoucherDetail> GJVoucherDetails { get; set; }
        public virtual DbSet<GLBeginningBalance> GLBeginningBalances { get; set; }
        public virtual DbSet<GLYear> GLYears { get; set; }
        public virtual DbSet<GradeCollege> GradeColleges { get; set; }
        public virtual DbSet<GradeCredit> GradeCredits { get; set; }
        public virtual DbSet<GradeDoctoral> GradeDoctorals { get; set; }
        public virtual DbSet<GradeElementary> GradeElementaries { get; set; }
        public virtual DbSet<GradeElemOld> GradeElemOlds { get; set; }
        public virtual DbSet<GradeJH> GradeJHS { get; set; }
        public virtual DbSet<GradeKinder> GradeKinders { get; set; }
        public virtual DbSet<GradeKinderDetail> GradeKinderDetails { get; set; }
        public virtual DbSet<GradeKinderQuestion> GradeKinderQuestions { get; set; }
        public virtual DbSet<GradeKinderQuestionSubject> GradeKinderQuestionSubjects { get; set; }
        public virtual DbSet<GradeKinderRemark> GradeKinderRemarks { get; set; }
        public virtual DbSet<GradeMasteral> GradeMasterals { get; set; }
        public virtual DbSet<GradeSH> GradeSHS { get; set; }
        public virtual DbSet<GraduationApplication> GraduationApplications { get; set; }
        public virtual DbSet<GuidanceEvent> GuidanceEvents { get; set; }
        public virtual DbSet<GuidanceImportantPerson> GuidanceImportantPersons { get; set; }
        public virtual DbSet<GuidanceOtherPeople> GuidanceOtherPeoples { get; set; }
        public virtual DbSet<GuidancePersonalDescription> GuidancePersonalDescriptions { get; set; }
        public virtual DbSet<GuidanceProblemChecklist> GuidanceProblemChecklists { get; set; }
        public virtual DbSet<GuidanceQuestionType> GuidanceQuestionTypes { get; set; }
        public virtual DbSet<GuidanceReferral> GuidanceReferrals { get; set; }
        public virtual DbSet<GuidanceReferralReason> GuidanceReferralReasons { get; set; }
        public virtual DbSet<GuidanceReferralReasonAnswer> GuidanceReferralReasonAnswers { get; set; }
        public virtual DbSet<GuidanceSeminar> GuidanceSeminars { get; set; }
        public virtual DbSet<GuidanceSibling> GuidanceSiblings { get; set; }
        public virtual DbSet<GuidanceStudentEvent> GuidanceStudentEvents { get; set; }
        public virtual DbSet<GuidanceStudentInfo> GuidanceStudentInfoes { get; set; }
        public virtual DbSet<GuidanceStudentSeminar> GuidanceStudentSeminars { get; set; }
        public virtual DbSet<GuidanceStudentTest> GuidanceStudentTests { get; set; }
        public virtual DbSet<GuidanceSurvey> GuidanceSurveys { get; set; }
        public virtual DbSet<GuidanceSurveyAnswer> GuidanceSurveyAnswers { get; set; }
        public virtual DbSet<GuidanceSurveyAnswerConcern> GuidanceSurveyAnswerConcerns { get; set; }
        public virtual DbSet<GuidanceSurveyAnswerDetail> GuidanceSurveyAnswerDetails { get; set; }
        public virtual DbSet<GuidanceSurveyDetail> GuidanceSurveyDetails { get; set; }
        public virtual DbSet<GuidanceSurveyQuestion> GuidanceSurveyQuestions { get; set; }
        public virtual DbSet<GuidanceTest> GuidanceTests { get; set; }
        public virtual DbSet<Holiday> Holidays { get; set; }
        public virtual DbSet<HRISActivityType> HRISActivityTypes { get; set; }
        public virtual DbSet<HRISApplicationCertificateEmployment> HRISApplicationCertificateEmployments { get; set; }
        public virtual DbSet<HRISBiometricsUser> HRISBiometricsUsers { get; set; }
        public virtual DbSet<HRISChangeVacationLeave> HRISChangeVacationLeaves { get; set; }
        public virtual DbSet<HRISChangeVacationLeaveDetail> HRISChangeVacationLeaveDetails { get; set; }
        public virtual DbSet<HRISLeaveCancellation> HRISLeaveCancellations { get; set; }
        public virtual DbSet<HRISMakeUpClass> HRISMakeUpClasses { get; set; }
        public virtual DbSet<HRISMakeUpClassDetail> HRISMakeUpClassDetails { get; set; }
        public virtual DbSet<HRISNoticeofAbsence> HRISNoticeofAbsences { get; set; }
        public virtual DbSet<HRISOffCampusActivity> HRISOffCampusActivities { get; set; }
        public virtual DbSet<HRISOnlineJobApplication> HRISOnlineJobApplications { get; set; }
        public virtual DbSet<HRISOnlineJobApplicationEducation> HRISOnlineJobApplicationEducations { get; set; }
        public virtual DbSet<HRISOnlineJobApplicationLicens> HRISOnlineJobApplicationLicenses { get; set; }
        public virtual DbSet<HRISOnlineJobApplicationSeminar> HRISOnlineJobApplicationSeminars { get; set; }
        public virtual DbSet<HRISOnlineJobApplicationStatu> HRISOnlineJobApplicationStatus { get; set; }
        public virtual DbSet<HRISOnlineJobApplicationWorkExperience> HRISOnlineJobApplicationWorkExperiences { get; set; }
        public virtual DbSet<HRISOvertime> HRISOvertimes { get; set; }
        public virtual DbSet<HRISOvertimeDetail> HRISOvertimeDetails { get; set; }
        public virtual DbSet<HRISPostTraining> HRISPostTrainings { get; set; }
        public virtual DbSet<HRISSubstituteClass> HRISSubstituteClasses { get; set; }
        public virtual DbSet<HRISSubstituteDetail> HRISSubstituteDetails { get; set; }
        public virtual DbSet<Institutional> Institutionals { get; set; }
        public virtual DbSet<JournalVoucher> JournalVouchers { get; set; }
        public virtual DbSet<JVDetail> JVDetails { get; set; }
        public virtual DbSet<Lab> Labs { get; set; }
        public virtual DbSet<LeaveApprovedStatu> LeaveApprovedStatus { get; set; }
        public virtual DbSet<LeaveCredit> LeaveCredits { get; set; }
        public virtual DbSet<LeaveType> LeaveTypes { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<Miscellaneou> Miscellaneous { get; set; }
        public virtual DbSet<ORSery> ORSeries { get; set; }
        public virtual DbSet<OtherClient> OtherClients { get; set; }
        public virtual DbSet<Others> Others { get; set; }
        public virtual DbSet<Paycode> Paycodes { get; set; }
        public virtual DbSet<Payee> Payees { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<PaymentDetail> PaymentDetails { get; set; }
        public virtual DbSet<Paymode> Paymodes { get; set; }
        public virtual DbSet<PaySchedule> PaySchedules { get; set; }
        public virtual DbSet<Period> Periods { get; set; }
        public virtual DbSet<Permit> Permits { get; set; }
        public virtual DbSet<PermitParameter> PermitParameters { get; set; }
        public virtual DbSet<PermitType> PermitTypes { get; set; }
        public virtual DbSet<PreReq> PreReqs { get; set; }
        public virtual DbSet<Proficiency> Proficiencies { get; set; }
        public virtual DbSet<Progam> Progams { get; set; }
        public virtual DbSet<ProgamCurriculum> ProgamCurriculums { get; set; }
        public virtual DbSet<ProjectedStat> ProjectedStats { get; set; }
        public virtual DbSet<Promissory> Promissories { get; set; }
        public virtual DbSet<Queue> Queues { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<RegistrarLog> RegistrarLogs { get; set; }
        public virtual DbSet<Requirement> Requirements { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<Schedule> Schedules { get; set; }
        public virtual DbSet<ScheduleStatu> ScheduleStatus { get; set; }
        public virtual DbSet<SchoolDaysElementary> SchoolDaysElementaries { get; set; }
        public virtual DbSet<SchoolDaysKinder> SchoolDaysKinders { get; set; }
        public virtual DbSet<SchoolYear> SchoolYears { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<SickLeaveType> SickLeaveTypes { get; set; }
        public virtual DbSet<Signatory> Signatories { get; set; }
        public virtual DbSet<sisItem> sisItems { get; set; }
        public virtual DbSet<sisSH> sisSHS { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Student_Curriculum> Student_Curriculum { get; set; }
        public virtual DbSet<Student_Requirement> Student_Requirement { get; set; }
        public virtual DbSet<Student_Section> Student_Section { get; set; }
        public virtual DbSet<StudentApplication> StudentApplications { get; set; }
        public virtual DbSet<StudentClearance> StudentClearances { get; set; }
        public virtual DbSet<StudentCurriculumStatu> StudentCurriculumStatus { get; set; }
        public virtual DbSet<StudentDemographic> StudentDemographics { get; set; }
        public virtual DbSet<StudentMaxUnit> StudentMaxUnits { get; set; }
        public virtual DbSet<StudentSchedule> StudentSchedules { get; set; }
        public virtual DbSet<StudentStatu> StudentStatus { get; set; }
        public virtual DbSet<StudentWithQualifying> StudentWithQualifyings { get; set; }
        public virtual DbSet<SubChartOfAccount> SubChartOfAccounts { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<SubjectElective> SubjectElectives { get; set; }
        public virtual DbSet<SubjectEquivalent> SubjectEquivalents { get; set; }
        public virtual DbSet<Supplemental> Supplementals { get; set; }
        public virtual DbSet<SystemParameter> SystemParameters { get; set; }
        public virtual DbSet<Technician> Technicians { get; set; }
        public virtual DbSet<TechnicianServiceRequisition> TechnicianServiceRequisitions { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<TShirt> TShirts { get; set; }
        public virtual DbSet<Tuition> Tuitions { get; set; }
        public virtual DbSet<Variou> Various { get; set; }
        public virtual DbSet<Zipcode> Zipcodes { get; set; }
        public virtual DbSet<back2016> back2016 { get; set; }
        public virtual DbSet<BackAccountCopy> BackAccountCopies { get; set; }
        public virtual DbSet<backaccounth> backaccounths { get; set; }
        public virtual DbSet<backelem> backelems { get; set; }
        public virtual DbSet<backpayment20161stsem> backpayment20161stsem { get; set; }
        public virtual DbSet<coaold> coaolds { get; set; }
        public virtual DbSet<cocurr2015> cocurr2015 { get; set; }
        public virtual DbSet<cocurr2016> cocurr2016 { get; set; }
        public virtual DbSet<CollegeCurriculum> CollegeCurriculums { get; set; }
        public virtual DbSet<GraduateCurriculum> GraduateCurriculums { get; set; }
        public virtual DbSet<HSClubMember> HSClubMembers { get; set; }
        public virtual DbSet<intranet_leave_tran> intranet_leave_tran { get; set; }
        public virtual DbSet<SeniorHighCurriculum> SeniorHighCurriculums { get; set; }
        public virtual DbSet<HRISEmployeeSchedule> HRISEmployeeSchedules { get; set; }
        public virtual DbSet<HRISShift> HRISShifts { get; set; }
        public virtual DbSet<BiometricsLogData> BiometricsLogDatas { get; set; }
        public virtual DbSet<EmploymentType> EmploymentTypes { get; set; }
        public virtual DbSet<HRISEmployeeAbsent> HRISEmployeeAbsents { get; set; }
        public virtual DbSet<LeaveBalance> LeaveBalances { get; set; }
        public virtual DbSet<Leave> Leaves { get; set; }
        public virtual DbSet<EmployeeHistory> EmployeeHistories { get; set; }
    
        public virtual ObjectResult<GetHRiSBirthdayCelebrants_Result> GetHRiSBirthdayCelebrants(Nullable<int> mONTH_KEY)
        {
            var mONTH_KEYParameter = mONTH_KEY.HasValue ?
                new ObjectParameter("MONTH_KEY", mONTH_KEY) :
                new ObjectParameter("MONTH_KEY", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHRiSBirthdayCelebrants_Result>("GetHRiSBirthdayCelebrants", mONTH_KEYParameter);
        }
    
        public virtual ObjectResult<GetHRiSEmployeebyDepartment_Result> GetHRiSEmployeebyDepartment()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHRiSEmployeebyDepartment_Result>("GetHRiSEmployeebyDepartment");
        }
    
        public virtual ObjectResult<GetHRiSEmployeebyStatus_Result> GetHRiSEmployeebyStatus()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHRiSEmployeebyStatus_Result>("GetHRiSEmployeebyStatus");
        }
    
        public virtual ObjectResult<GetHRiSLeaveApproved_Result> GetHRiSLeaveApproved()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHRiSLeaveApproved_Result>("GetHRiSLeaveApproved");
        }
    
        public virtual ObjectResult<GetHRiSLeaveBalances_Result> GetHRiSLeaveBalances()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHRiSLeaveBalances_Result>("GetHRiSLeaveBalances");
        }
    
        public virtual ObjectResult<GetHRiSLeaveCancelled_Result> GetHRiSLeaveCancelled()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHRiSLeaveCancelled_Result>("GetHRiSLeaveCancelled");
        }
    
        public virtual ObjectResult<GetHRiSLeaveEmployeeHistory_Result> GetHRiSLeaveEmployeeHistory(Nullable<int> eMPID_KEY)
        {
            var eMPID_KEYParameter = eMPID_KEY.HasValue ?
                new ObjectParameter("EMPID_KEY", eMPID_KEY) :
                new ObjectParameter("EMPID_KEY", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHRiSLeaveEmployeeHistory_Result>("GetHRiSLeaveEmployeeHistory", eMPID_KEYParameter);
        }
    
        public virtual ObjectResult<GetHRiSLeaveOnProcess_Result> GetHRiSLeaveOnProcess()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHRiSLeaveOnProcess_Result>("GetHRiSLeaveOnProcess");
        }
    
        public virtual ObjectResult<GetHRiSListbyAge_Result> GetHRiSListbyAge()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHRiSListbyAge_Result>("GetHRiSListbyAge");
        }
    
        public virtual ObjectResult<GetHRiSListbyGender_Result> GetHRiSListbyGender()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHRiSListbyGender_Result>("GetHRiSListbyGender");
        }
    
        public virtual ObjectResult<GetHRiSServiceAwardees_Result> GetHRiSServiceAwardees(Nullable<int> yR_KEY)
        {
            var yR_KEYParameter = yR_KEY.HasValue ?
                new ObjectParameter("YR_KEY", yR_KEY) :
                new ObjectParameter("YR_KEY", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHRiSServiceAwardees_Result>("GetHRiSServiceAwardees", yR_KEYParameter);
        }
    
        public virtual ObjectResult<GetHRiSsisPerFaculty_Result> GetHRiSsisPerFaculty(Nullable<int> pERID_KEY, Nullable<int> fACID_KEY)
        {
            var pERID_KEYParameter = pERID_KEY.HasValue ?
                new ObjectParameter("PERID_KEY", pERID_KEY) :
                new ObjectParameter("PERID_KEY", typeof(int));
    
            var fACID_KEYParameter = fACID_KEY.HasValue ?
                new ObjectParameter("FACID_KEY", fACID_KEY) :
                new ObjectParameter("FACID_KEY", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHRiSsisPerFaculty_Result>("GetHRiSsisPerFaculty", pERID_KEYParameter, fACID_KEYParameter);
        }
    
        public virtual ObjectResult<GetHRiSsisPerSchedule_Result> GetHRiSsisPerSchedule(Nullable<int> pERID_KEY, Nullable<int> sCHDID_KEY)
        {
            var pERID_KEYParameter = pERID_KEY.HasValue ?
                new ObjectParameter("PERID_KEY", pERID_KEY) :
                new ObjectParameter("PERID_KEY", typeof(int));
    
            var sCHDID_KEYParameter = sCHDID_KEY.HasValue ?
                new ObjectParameter("SCHDID_KEY", sCHDID_KEY) :
                new ObjectParameter("SCHDID_KEY", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHRiSsisPerSchedule_Result>("GetHRiSsisPerSchedule", pERID_KEYParameter, sCHDID_KEYParameter);
        }
    
        public virtual ObjectResult<GetHRiSLeaveUsage_Result> GetHRiSLeaveUsage(Nullable<System.DateTime> sTARTDATE_KEY, Nullable<System.DateTime> eNDDATE_KEY)
        {
            var sTARTDATE_KEYParameter = sTARTDATE_KEY.HasValue ?
                new ObjectParameter("STARTDATE_KEY", sTARTDATE_KEY) :
                new ObjectParameter("STARTDATE_KEY", typeof(System.DateTime));
    
            var eNDDATE_KEYParameter = eNDDATE_KEY.HasValue ?
                new ObjectParameter("ENDDATE_KEY", eNDDATE_KEY) :
                new ObjectParameter("ENDDATE_KEY", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHRiSLeaveUsage_Result>("GetHRiSLeaveUsage", sTARTDATE_KEYParameter, eNDDATE_KEYParameter);
        }
    
        public virtual ObjectResult<GetHRiSLeaveTransactionReport_Result> GetHRiSLeaveTransactionReport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHRiSLeaveTransactionReport_Result>("GetHRiSLeaveTransactionReport");
        }
    
        public virtual ObjectResult<GetEmployeeAttendance_Result> GetEmployeeAttendance(string startDate, string endDate)
        {
            var startDateParameter = startDate != null ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(string));
    
            var endDateParameter = endDate != null ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEmployeeAttendance_Result>("GetEmployeeAttendance", startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<GetEmployeeAttendanceByEmployeeNumber_Result> GetEmployeeAttendanceByEmployeeNumber(string startDate, string endDate, string employeeNumber)
        {
            var startDateParameter = startDate != null ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(string));
    
            var endDateParameter = endDate != null ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(string));
    
            var employeeNumberParameter = employeeNumber != null ?
                new ObjectParameter("employeeNumber", employeeNumber) :
                new ObjectParameter("employeeNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEmployeeAttendanceByEmployeeNumber_Result>("GetEmployeeAttendanceByEmployeeNumber", startDateParameter, endDateParameter, employeeNumberParameter);
        }
    
        public virtual ObjectResult<GetEmployeeAttendanceTest_Result> GetEmployeeAttendanceTest(string startDate, string endDate, Nullable<int> bioid)
        {
            var startDateParameter = startDate != null ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(string));
    
            var endDateParameter = endDate != null ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(string));
    
            var bioidParameter = bioid.HasValue ?
                new ObjectParameter("bioid", bioid) :
                new ObjectParameter("bioid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEmployeeAttendanceTest_Result>("GetEmployeeAttendanceTest", startDateParameter, endDateParameter, bioidParameter);
        }
    
        public virtual ObjectResult<GetEmployeeDTR_Result> GetEmployeeDTR(string startDate, string endDate, Nullable<int> bioid)
        {
            var startDateParameter = startDate != null ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(string));
    
            var endDateParameter = endDate != null ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(string));
    
            var bioidParameter = bioid.HasValue ?
                new ObjectParameter("bioid", bioid) :
                new ObjectParameter("bioid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEmployeeDTR_Result>("GetEmployeeDTR", startDateParameter, endDateParameter, bioidParameter);
        }
    }
}
