//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paycode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paycode()
        {
            this.PaymentDetails = new HashSet<PaymentDetail>();
            this.PaySchedules = new HashSet<PaySchedule>();
        }
    
        public int PaycodeID { get; set; }
        public string Description { get; set; }
        public Nullable<double> Amount { get; set; }
        public bool Active { get; set; }
        public bool TuitionRelated { get; set; }
        public Nullable<int> COANo { get; set; }
        public Nullable<int> SubCOANo { get; set; }
    
        public virtual ChartOfAccount ChartOfAccount { get; set; }
        public virtual SubChartOfAccount SubChartOfAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentDetail> PaymentDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaySchedule> PaySchedules { get; set; }
    }
}
