//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment()
        {
            this.Adjustments = new HashSet<Adjustment>();
            this.BackAccounts = new HashSet<BackAccount>();
            this.BackAccountPayments = new HashSet<BackAccountPayment>();
            this.PaymentDetails = new HashSet<PaymentDetail>();
        }
    
        public int PaymentID { get; set; }
        public string ORNo { get; set; }
        public int CashierID { get; set; }
        public byte[] Datestamp { get; set; }
        public System.DateTime DateReceived { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string Bank { get; set; }
        public Nullable<double> CheckAmount { get; set; }
        public string CheckNo { get; set; }
        public Nullable<int> SemID { get; set; }
        public string Branch { get; set; }
        public Nullable<int> EducLevel { get; set; }
        public Nullable<int> CurriculumID { get; set; }
        public Nullable<int> OtherClientID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adjustment> Adjustments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BackAccount> BackAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BackAccountPayment> BackAccountPayments { get; set; }
        public virtual Curriculum Curriculum { get; set; }
        public virtual EducationalLevel EducationalLevel { get; set; }
        public virtual OtherClient OtherClient { get; set; }
        public virtual Period Period { get; set; }
        public virtual Student Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentDetail> PaymentDetails { get; set; }
    }
}
