//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proficiency
    {
        public int ProficiencyID { get; set; }
        public Nullable<int> SectionID { get; set; }
        public string Gender { get; set; }
        public string ProficiencyName { get; set; }
        public Nullable<int> Sequence { get; set; }
    
        public virtual Section Section { get; set; }
    }
}
