//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectedStat
    {
        public string Description { get; set; }
        public Nullable<int> EducLevel { get; set; }
        public int SemID { get; set; }
        public Nullable<int> Total { get; set; }
        public int CurriculumID { get; set; }
        public int YearLevel { get; set; }
    
        public virtual EducationalLevel EducationalLevel { get; set; }
        public virtual Period Period { get; set; }
        public virtual Progam Progam { get; set; }
    }
}
