//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promissory
    {
        public int PNID { get; set; }
        public Nullable<int> Student_SectionID { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> Validity { get; set; }
        public Nullable<System.DateTime> PNDate { get; set; }
        public Nullable<double> Amount { get; set; }
        public string PNFor { get; set; }
        public Nullable<bool> Settled { get; set; }
    
        public virtual Student_Section Student_Section { get; set; }
    }
}
