//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class room2017
    {
        public string room_code { get; set; }
        public string room_desc { get; set; }
        public bool aircon { get; set; }
        public string dept { get; set; }
        public Nullable<double> capacity { get; set; }
    }
}
