//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Schedule()
        {
            this.AdjustmentDetails = new HashSet<AdjustmentDetail>();
            this.HRISMakeUpClassDetails = new HashSet<HRISMakeUpClassDetail>();
            this.HRISSubstituteDetails = new HashSet<HRISSubstituteDetail>();
            this.StudentSchedules = new HashSet<StudentSchedule>();
        }
    
        public int ScheduleID { get; set; }
        public string Days { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<int> FacultyID { get; set; }
        public int SubjectID { get; set; }
        public int SectionID { get; set; }
        public Nullable<int> ReservedSlot { get; set; }
        public Nullable<int> MaxSlot { get; set; }
        public Nullable<int> ScheduleStatusID { get; set; }
        public Nullable<int> SectionID2 { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DatePrintedOnline { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdjustmentDetail> AdjustmentDetails { get; set; }
        public virtual Faculty Faculty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRISMakeUpClassDetail> HRISMakeUpClassDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRISSubstituteDetail> HRISSubstituteDetails { get; set; }
        public virtual Room Room { get; set; }
        public virtual Section Section { get; set; }
        public virtual Subject Subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentSchedule> StudentSchedules { get; set; }
        public virtual ScheduleStatu ScheduleStatu { get; set; }
        public virtual Section Section1 { get; set; }
    }
}
