//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class schedule2017
    {
        public Nullable<double> sub_id { get; set; }
        public string period { get; set; }
        public string sectno { get; set; }
        public string subcode { get; set; }
        public string extend { get; set; }
        public string room { get; set; }
        public string gr_yr { get; set; }
        public string days { get; set; }
        public string timefr { get; set; }
        public string timeto { get; set; }
        public string fcode { get; set; }
        public Nullable<double> warning { get; set; }
        public Nullable<double> max_stud { get; set; }
        public Nullable<double> tot_stud { get; set; }
        public string coll_ind { get; set; }
        public string var { get; set; }
        public bool @lock { get; set; }
        public Nullable<double> i_code { get; set; }
        public string binary { get; set; }
        public string colcode { get; set; }
    }
}
