//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolDaysKinder
    {
        public int SchoolDaysKinderID { get; set; }
        public Nullable<int> PeriodID { get; set; }
        public Nullable<int> Jun { get; set; }
        public Nullable<int> Jul { get; set; }
        public Nullable<int> AuG { get; set; }
        public Nullable<int> Sept { get; set; }
        public Nullable<int> Oct { get; set; }
        public Nullable<int> Nov { get; set; }
        public Nullable<int> Dec { get; set; }
        public Nullable<int> Jan { get; set; }
        public Nullable<int> Feb { get; set; }
        public Nullable<int> Mar { get; set; }
        public Nullable<int> Apr { get; set; }
        public Nullable<int> Term { get; set; }
        public Nullable<int> YearLevel { get; set; }
    
        public virtual Period Period { get; set; }
    }
}
