//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Signatory
    {
        public int SignatoryID { get; set; }
        public Nullable<int> PeriodID { get; set; }
        public Nullable<int> EducLevelID { get; set; }
        public string Signatory1 { get; set; }
        public string Signatory2 { get; set; }
        public string Signatory3 { get; set; }
        public string Signatory4 { get; set; }
    }
}
