//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sisItem
    {
        public int sisItemID { get; set; }
        public Nullable<int> sisCatID { get; set; }
        public string sisItem1 { get; set; }
        public Nullable<decimal> sisItemweight { get; set; }
        public Nullable<int> dept { get; set; }
    }
}
