//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sisSH
    {
        public int sisSHSID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> ScheduleID { get; set; }
        public string Comment1 { get; set; }
        public string Comment2 { get; set; }
        public string Comment3 { get; set; }
        public Nullable<int> Q1 { get; set; }
        public Nullable<int> Q2 { get; set; }
        public Nullable<int> Q3 { get; set; }
        public Nullable<int> Q4 { get; set; }
        public Nullable<int> Q5 { get; set; }
        public Nullable<int> Q6 { get; set; }
        public Nullable<int> Q7 { get; set; }
        public Nullable<int> Q8 { get; set; }
        public Nullable<int> Q9 { get; set; }
        public Nullable<int> Q10 { get; set; }
        public Nullable<int> Q11 { get; set; }
        public Nullable<int> Q12 { get; set; }
        public Nullable<int> Q13 { get; set; }
        public Nullable<int> Q14 { get; set; }
        public Nullable<int> Q15 { get; set; }
        public Nullable<int> Q16 { get; set; }
        public Nullable<int> Q17 { get; set; }
        public Nullable<int> Q18 { get; set; }
        public Nullable<int> Q19 { get; set; }
        public Nullable<int> Q20 { get; set; }
        public Nullable<int> Q21 { get; set; }
        public Nullable<int> Q22 { get; set; }
        public Nullable<int> Q23 { get; set; }
        public Nullable<int> Q24 { get; set; }
        public Nullable<int> Q25 { get; set; }
        public Nullable<int> Q26 { get; set; }
        public string StudentNo { get; set; }
        public string SubCode { get; set; }
        public string SecNo { get; set; }
        public string fcode { get; set; }
        public Nullable<int> StudentScheduleID { get; set; }
        public Nullable<System.DateTime> EvaluationDate { get; set; }
        public byte[] Timestamp { get; set; }
        public Nullable<int> Q27 { get; set; }
        public Nullable<int> Q28 { get; set; }
    
        public virtual StudentSchedule StudentSchedule { get; set; }
    }
}
