//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Section
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student_Section()
        {
            this.Adjustments = new HashSet<Adjustment>();
            this.ARMessages = new HashSet<ARMessage>();
            this.Assessments = new HashSet<Assessment>();
            this.BackAccounts = new HashSet<BackAccount>();
            this.PaymentDetails = new HashSet<PaymentDetail>();
            this.Promissories = new HashSet<Promissory>();
            this.StudentSchedules = new HashSet<StudentSchedule>();
        }
    
        public int Student_SectionID { get; set; }
        public int StudentID { get; set; }
        public int SectionID { get; set; }
        public Nullable<int> PaymodeID { get; set; }
        public bool NewStatus { get; set; }
        public Nullable<System.DateTime> EnlistmentDate { get; set; }
        public string EncodedBy { get; set; }
        public Nullable<System.DateTime> ValidationDate { get; set; }
        public Nullable<int> CurriculumID { get; set; }
        public Nullable<System.DateTime> DatePrinted { get; set; }
        public int Status { get; set; }
        public Nullable<double> TuitionFee { get; set; }
        public Nullable<double> MiscFee { get; set; }
        public Nullable<double> SuppFee { get; set; }
        public Nullable<double> LabFee { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> Net { get; set; }
        public Nullable<double> DownPayment { get; set; }
        public Nullable<double> SecondPayment { get; set; }
        public Nullable<double> Credit { get; set; }
        public Nullable<System.DateTime> AssessmentDate { get; set; }
        public string AssessedBy { get; set; }
        public bool Locked { get; set; }
        public Nullable<int> StudentStatus { get; set; }
        public Nullable<int> SectionID2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adjustment> Adjustments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARMessage> ARMessages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Assessment> Assessments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BackAccount> BackAccounts { get; set; }
        public virtual Curriculum Curriculum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentDetail> PaymentDetails { get; set; }
        public virtual Paymode Paymode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Promissory> Promissories { get; set; }
        public virtual Section Section { get; set; }
        public virtual Student Student { get; set; }
        public virtual StudentStatu StudentStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentSchedule> StudentSchedules { get; set; }
    }
}
