//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDemographic
    {
        public int StudentID { get; set; }
        public string Gender { get; set; }
        public string CivilStatus { get; set; }
        public string Citizenship { get; set; }
        public string Religion { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Birthplace { get; set; }
        public string Address { get; set; }
        public string District { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string Country { get; set; }
        public string PAddress { get; set; }
        public string PDistrict { get; set; }
        public string PCity { get; set; }
        public string PProvince { get; set; }
        public string Dwelling { get; set; }
        public string Homeown { get; set; }
        public Nullable<int> Homeown_yr { get; set; }
        public Nullable<int> Homeown_mo { get; set; }
        public string Lastschool { get; set; }
        public string Lastschool_type { get; set; }
        public string StudentWorking { get; set; }
        public string Father_Lastname { get; set; }
        public string Father_MI { get; set; }
        public string Father_Firstname { get; set; }
        public string Father_highesteduc { get; set; }
        public string Father_Occup { get; set; }
        public string Father_Company { get; set; }
        public string Father_CompanyAddress { get; set; }
        public string Father_Contact { get; set; }
        public string Mother_Lastname { get; set; }
        public string Mother_MI { get; set; }
        public string Mother_Firstname { get; set; }
        public string Mother_highesteduc { get; set; }
        public string Mother_Occup { get; set; }
        public string Mother_Company { get; set; }
        public string Mother_CompanyAddress { get; set; }
        public string Mother_Contact { get; set; }
        public string Guardian_Lastname { get; set; }
        public string Guardian_MI { get; set; }
        public string Guardian_Firstname { get; set; }
        public string Guardian_highesteduc { get; set; }
        public string Guardian_Occup { get; set; }
        public string Guardian_Company { get; set; }
        public string Guardian_CompanyAddress { get; set; }
        public string Guardian_Contact { get; set; }
        public Nullable<int> Siblings { get; set; }
        public Nullable<int> Siblings_Ordinal { get; set; }
        public Nullable<int> Siblings_Elem { get; set; }
        public Nullable<int> Siblings_HS { get; set; }
        public Nullable<int> Siblings_College { get; set; }
        public Nullable<int> Siblings_Working { get; set; }
        public string Finance_Source { get; set; }
        public string Income_bracket { get; set; }
        public string Income_source { get; set; }
        public string Transportation_Mode { get; set; }
        public string Monetary_Allowance_Mode { get; set; }
        public Nullable<double> Monetary_Allowance_Value { get; set; }
        public string LearnAboutLetran { get; set; }
        public string DecideToEnrollLetran { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
