//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentClearance
    {
        public int StudentMOAID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> DateIssued { get; set; }
        public string IssuedBy { get; set; }
        public string UnblockBy { get; set; }
        public string UntagBy { get; set; }
        public Nullable<bool> Block { get; set; }
        public bool Tag { get; set; }
        public Nullable<int> IssuedByID { get; set; }
        public Nullable<int> UnblockedByID { get; set; }
        public Nullable<int> UntaggedByID { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
