//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Requirement
    {
        public int StudentRequirementID { get; set; }
        public int StudentID { get; set; }
        public int RequirementID { get; set; }
        public System.DateTime DateCompletion { get; set; }
    
        public virtual Requirement Requirement { get; set; }
        public virtual Student Student { get; set; }
    }
}
