//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentApplication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentApplication()
        {
            this.AdmissionExamResults = new HashSet<AdmissionExamResult>();
            this.ApplicationEncourageDetails = new HashSet<ApplicationEncourageDetail>();
            this.ApplicationPlanDetails = new HashSet<ApplicationPlanDetail>();
            this.ApplicationSurveyDetails = new HashSet<ApplicationSurveyDetail>();
        }
    
        public int ApplicationNo { get; set; }
        public Nullable<int> ExamDateID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string ORNO { get; set; }
        public byte[] Photo { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string PostalCode { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string LandlineNo { get; set; }
        public string MobileNo { get; set; }
        public string Citizenship { get; set; }
        public string CivilStatus { get; set; }
        public string Religion { get; set; }
        public string Gender { get; set; }
        public string FatherName { get; set; }
        public string FatherContact { get; set; }
        public string FatherOccupation { get; set; }
        public string FatherEmployer { get; set; }
        public string FatherEmail { get; set; }
        public string MotherName { get; set; }
        public string MotherContact { get; set; }
        public string MotherOccupation { get; set; }
        public string MotherEmployer { get; set; }
        public string MotherEmail { get; set; }
        public string GuardianName { get; set; }
        public string GuardianAddress { get; set; }
        public string RelationshipToGuardian { get; set; }
        public string GuardianContactNo { get; set; }
        public Nullable<int> EducationLevel { get; set; }
        public string FirstChoice { get; set; }
        public string SecondChoice { get; set; }
        public string TypeOfApplication { get; set; }
        public string FormerSchool { get; set; }
        public string FormerSchoolAddress { get; set; }
        public string GraduationYear { get; set; }
        public Nullable<double> GPA { get; set; }
        public string HonorsReceived { get; set; }
        public string SchoolLastAttended { get; set; }
        public string SchoolLastAttendedCourse { get; set; }
        public string Encoder { get; set; }
        public Nullable<System.DateTime> DateEncoded { get; set; }
        public Nullable<System.DateTime> DatePrinted { get; set; }
        public Nullable<int> YearEntry { get; set; }
        public string SchooLastAttendedType { get; set; }
        public string GradeLevel { get; set; }
    
        public virtual AdmissionExamDate AdmissionExamDate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdmissionExamResult> AdmissionExamResults { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationEncourageDetail> ApplicationEncourageDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationPlanDetail> ApplicationPlanDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationSurveyDetail> ApplicationSurveyDetails { get; set; }
        public virtual EducationalLevel EducationalLevel { get; set; }
        public virtual Period Period { get; set; }
    }
}
