//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubChartOfAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubChartOfAccount()
        {
            this.CDSVoucherDetails = new HashSet<CDSVoucherDetail>();
            this.DiscountCategories = new HashSet<DiscountCategory>();
            this.DiscountTypes = new HashSet<DiscountType>();
            this.DMCMs = new HashSet<DMCM>();
            this.Fees = new HashSet<Fee>();
            this.GLBeginningBalances = new HashSet<GLBeginningBalance>();
            this.Paycodes = new HashSet<Paycode>();
            this.CRSVoucherDetails = new HashSet<CRSVoucherDetail>();
        }
    
        public int SubAcctID { get; set; }
        public string SubAcctNo { get; set; }
        public string SubbAcctName { get; set; }
        public Nullable<int> AcctID { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> PayeeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CDSVoucherDetail> CDSVoucherDetails { get; set; }
        public virtual ChartOfAccount ChartOfAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiscountCategory> DiscountCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiscountType> DiscountTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DMCM> DMCMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fee> Fees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GLBeginningBalance> GLBeginningBalances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paycode> Paycodes { get; set; }
        public virtual Payee Payee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRSVoucherDetail> CRSVoucherDetails { get; set; }
    }
}
