//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class subject2017
    {
        public Nullable<double> sub_id { get; set; }
        public string gr_yr { get; set; }
        public string subcode { get; set; }
        public string subdesc { get; set; }
        public Nullable<double> units { get; set; }
        public string dept { get; set; }
        public string extend { get; set; }
        public string forcode { get; set; }
        public string s_order { get; set; }
        public bool n_acad { get; set; }
        public string lab_code { get; set; }
        public string var_code { get; set; }
        public string labacct { get; set; }
        public string print_col { get; set; }
        public string code { get; set; }
        public string colcode { get; set; }
    }
}
