//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subject()
        {
            this.BasicEducationOthers = new HashSet<BasicEducationOther>();
            this.ChangeOfGradeDoctorals = new HashSet<ChangeOfGradeDoctoral>();
            this.ChangeOfGradeMasterals = new HashSet<ChangeOfGradeMasteral>();
            this.Curriculum_Subject = new HashSet<Curriculum_Subject>();
            this.GradeColleges = new HashSet<GradeCollege>();
            this.GradeCredits = new HashSet<GradeCredit>();
            this.GradeDoctorals = new HashSet<GradeDoctoral>();
            this.GradeElementaries = new HashSet<GradeElementary>();
            this.GradeJHS = new HashSet<GradeJH>();
            this.GradeKinders = new HashSet<GradeKinder>();
            this.GradeKinderQuestionSubjects = new HashSet<GradeKinderQuestionSubject>();
            this.GradeMasterals = new HashSet<GradeMasteral>();
            this.GradeSHS = new HashSet<GradeSH>();
            this.Labs = new HashSet<Lab>();
            this.Others = new HashSet<Others>();
            this.PreReqs = new HashSet<PreReq>();
            this.PreReqs1 = new HashSet<PreReq>();
            this.Schedules = new HashSet<Schedule>();
            this.Subject1 = new HashSet<Subject>();
            this.SubjectElectives = new HashSet<SubjectElective>();
            this.SubjectElectives1 = new HashSet<SubjectElective>();
            this.SubjectEquivalents = new HashSet<SubjectEquivalent>();
            this.SubjectEquivalents1 = new HashSet<SubjectEquivalent>();
        }
    
        public int SubjectID { get; set; }
        public string SubjectCode { get; set; }
        public string Description { get; set; }
        public double Units { get; set; }
        public Nullable<byte> S_CODE { get; set; }
        public Nullable<byte> N_CODE { get; set; }
        public Nullable<int> EducLevelID { get; set; }
        public Nullable<int> IndexKey { get; set; }
        public Nullable<bool> IsTuition { get; set; }
        public Nullable<bool> NAcad { get; set; }
        public Nullable<bool> IsHome { get; set; }
        public Nullable<double> NoOfHours { get; set; }
        public Nullable<int> MainSubjectID { get; set; }
        public Nullable<bool> IsOneYearComp { get; set; }
        public Nullable<bool> IsComponent { get; set; }
        public Nullable<int> AreaID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasicEducationOther> BasicEducationOthers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChangeOfGradeDoctoral> ChangeOfGradeDoctorals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChangeOfGradeMasteral> ChangeOfGradeMasterals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Curriculum_Subject> Curriculum_Subject { get; set; }
        public virtual EducationalLevel EducationalLevel { get; set; }
        public virtual FacultyArea FacultyArea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GradeCollege> GradeColleges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GradeCredit> GradeCredits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GradeDoctoral> GradeDoctorals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GradeElementary> GradeElementaries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GradeJH> GradeJHS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GradeKinder> GradeKinders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GradeKinderQuestionSubject> GradeKinderQuestionSubjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GradeMasteral> GradeMasterals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GradeSH> GradeSHS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lab> Labs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Others> Others { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreReq> PreReqs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreReq> PreReqs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subject> Subject1 { get; set; }
        public virtual Subject Subject2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubjectElective> SubjectElectives { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubjectElective> SubjectElectives1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubjectEquivalent> SubjectEquivalents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubjectEquivalent> SubjectEquivalents1 { get; set; }
    }
}
