//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemParameter
    {
        public int SysParameterID { get; set; }
        public int PeriodID { get; set; }
        public Nullable<int> TermID { get; set; }
        public Nullable<System.DateTime> SEncoding { get; set; }
        public Nullable<System.DateTime> EEncoding { get; set; }
        public Nullable<System.DateTime> SViewing { get; set; }
        public Nullable<System.DateTime> BalanceDate { get; set; }
        public Nullable<int> EducLevelID { get; set; }
        public Nullable<System.DateTime> SEvaluation { get; set; }
        public Nullable<System.DateTime> EEvaluation { get; set; }
        public Nullable<System.DateTime> VEvaluation { get; set; }
        public Nullable<System.DateTime> SEnlistment { get; set; }
        public Nullable<System.DateTime> EEnlistment { get; set; }
        public Nullable<System.DateTime> SAdjustment { get; set; }
        public Nullable<System.DateTime> EAdjustment { get; set; }
        public Nullable<System.DateTime> EEnrollmment { get; set; }
        public Nullable<System.DateTime> ERegularEnlistment { get; set; }
        public Nullable<System.DateTime> SEnrollment { get; set; }
    
        public virtual EducationalLevel EducationalLevel { get; set; }
        public virtual Period Period { get; set; }
    }
}
