//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbltimein
    {
        public long IDlog { get; set; }
        public string IDnumber { get; set; }
        public Nullable<System.DateTime> TimeIn { get; set; }
        public string FolderName { get; set; }
        public byte[] EntryCAp { get; set; }
        public string Status { get; set; }
    }
}
