//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRiS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIME00
    {
        public string EMPN { get; set; }
        public System.DateTime DTIME { get; set; }
        public string MODE { get; set; }
        public string TAG { get; set; }
    }
}
